feat: Avoid rate-limiting when fetching OSC
Remove the usage of the GitHub API to avoid any rate limiting.
The API was only used to retrieve the version of the `latest` version.

As this creates an issue in enterprise environments with shared IP
addresses and the usage of GHES, replace the API access with retrieving
the version from the location header of `/releases/latest`.

Signed-off-by: Marcel Bochtler <marcel.bochtler@bosch.com>

diff --git a/setup-osc/action.yml b/setup-osc/action.yml
--- a/setup-osc/action.yml
+++ b/setup-osc/action.yml
@@ -50,9 +50,13 @@ runs:
         fi
 
         if [[ -z "$OSC_VERSION" || "$OSC_VERSION" = "latest" ]]; then
-          OSC_VERSION=$(curl -s ${AUTH_HEADER:+-H "$AUTH_HEADER"} \
-            https://api.github.com/repos/eclipse-apoapsis/ort-server/releases/latest \
-            | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p')
+          OSC_VERSION=$(curl -sI https://github.com/eclipse-apoapsis/ort-server/releases/latest \
+            | grep -i "location" | sed 's,.*/tag/,,' | tr -d '\r\n')
+        
+          if [ -z "$OSC_VERSION" ]; then
+            echo "::error::Failed to get the latest OSC version."
+            exit 1
+          fi
         fi
 
         if [[ -z "$OSC_VERSION" || "$OSC_VERSION" = "null" ]]; then
